"use client";

//import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

// export const metadata: Metadata = {
//   title: "Stock Tracker",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex min-h-screen bg-gray-100 text-gray-800 font-sans">
        {/* Sidebar */}
        <aside className="w-64 bg-white shadow-lg p-6 flex flex-col space-y-8">
          <h1 className="text-xl font-semibold text-blue-700 uppercase">Stock Tracker</h1>
          <nav>
            <ul className="flex flex-col space-y-4 text-base font-medium">
              {[
                { label: "S&P 500", href: "/" },
                { label: "S&P MidCap 400", href: "/midcap" },
                { label: "S&P SmallCap 600", href: "/smallcap" },
                { label: "Dow Jones", href: "/dow-jones" },
                { label: "Watchlist", href: "/watchlist" },
                { label: "Alerts", href: "/alerts" },
                { label: "Settings", href: "/settings" },
              ].map(({ label, href }) => (
                <li key={href}>
                  <Link
                    href={href}
                    className="hover:text-blue-600 transition-colors duration-200"
                  >
                    {label}
                  </Link>
                </li>
              ))}
            </ul>
          </nav>
        </aside>

        {/* Main Content */}
        <main className="flex-1 p-8 overflow-y-auto">{children}</main>
      </body>
    </html>
  );
}