"use client";

//import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

// export const metadata: Metadata = {
//   title: "Stock Tracker",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex min-h-screen bg-gray-300">
        <aside className="w-64 bg-white shadow-md p-6 flex flex-col space-y-6">
          <h1 className="font-bold text-2xl">Stock Tracker</h1>
          <nav>
            <ul className="flex flex-col space-y-4 text-lg">
              <li>
                <Link href="/" className="hover:text-blue-600 transition-colors">S&P 500</Link>
              </li>
              <li>
                <Link href="/midcap" className="hover:text-blue-600 transition-colors">S&P MidCap 400</Link>
              </li>
              <li>
                <Link href="/smallcap" className="hover:text-blue-600 transition-colors">S&P SmallCap 600</Link>
              </li>
              <li>
                <Link href="/alerts" className="hover:text-blue-600 transition-colors">Alerts</Link>
              </li>
              <li>
                <Link href="/settings" className="hover:text-blue-600 transition-colors">Settings</Link>
              </li>
            </ul>
          </nav>
        </aside>
        <main>{children}</main>
      </body>
    </html>
  );
}